CREATE DATABASE IF NOT EXISTS flask_DB;

USE flask_DB

CREATE TABLE USERS (
ID INT AUTO_INCREMENT NOT NULL,
NOM VARCHAR(100),
PRENOM VARCHAR(100),
SEXE VARCHAR(100),
PSEUDO VARCHAR(100),
PRIMARY KEY(ID))
	
DEFAULT CHARACTER SET utf8
COLLATE utf8_unicode_ci
ENGINE = InnoDB;

